spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: "dasnafdsafasfasfasfasfasfsdfkandfklanddasfwweq"
  access-token-expiration-minutes: 1
  refresh-token-expiration-minutes: 420